#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldLighting

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// FortHomebaseBannerColorItem Transient.FortEngine_2147482594.FortGameInstance_2147482571.FortMcpProfileCommonCore_2147481911.FortHomebaseBannerColorItem_2147481893
// 0x0350 (0x0350 - 0x0000)
struct AWorldLighting_C final
{
public:
	uint8                                         Pad_0[0x350];                                      // 0x0000(0x0350)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(AWorldLighting_C) == 0x000008, "Wrong alignment on AWorldLighting_C");
static_assert(sizeof(AWorldLighting_C) == 0x000350, "Wrong size on AWorldLighting_C");

}

